In [1]:
import numpy as np

In [15]:
# Вектор списка

v = np.array([1, 2, 3, 4])
v

array([1, 2, 3, 4])

In [16]:
# вектор из нулей длиной 5

zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [18]:
# МАТРИЦА единичная 3*3

eye = np.eye(3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# Матрица 2*3 из случайных чисел

rand_matrix = np.random.rand(2, 3)
rand_matrix

array([[0.47978008, 0.37663457, 0.70448922],
       [0.33414525, 0.96810486, 0.45054789]])

In [23]:
v.shape

(4,)

In [24]:
v.ndim

1

In [27]:
v2 = np.zeros(12)
v2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
v2.reshape(3, 4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
v2.reshape(-1, 1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [34]:
a = [1, 2, 3]
b = [4, 5, 6]

In [35]:
a_v = np.array(a)
b_v = np.array(b)

In [36]:
a_v

array([1, 2, 3])

In [37]:
b_v

array([4, 5, 6])

In [38]:
a_v + b_v

array([5, 7, 9])

In [39]:
a_v - b_v

array([-3, -3, -3])

In [40]:
a_v * 3

array([3, 6, 9])

In [43]:
# скалярное произведение

a_v @ b_v

np.int64(32)

In [45]:
# поэлементальное произведение

a_v * b_v

array([ 4, 10, 18])

# NEXT

In [50]:
A = [[1, 2], [3, 4]]
A = np.array(A)
A

array([[1, 2],
       [3, 4]])

In [51]:
v = [5, 6]
v = np.array(v)
v

array([5, 6])

In [52]:
A * v

array([[ 5, 12],
       [15, 24]])

In [53]:
A @ v

array([17, 39])

In [56]:
A @ A

array([[ 7, 10],
       [15, 22]])

In [57]:
A.T

array([[1, 3],
       [2, 4]])

In [58]:
np.sum(A)

np.int64(10)

In [59]:
np.mean(A, axis=0)

array([2., 3.])

In [60]:
np.mean(A, axis=1)

array([1.5, 3.5])

# NEXT

In [61]:
cars = [
    [1945, 560, 4.3],
    [1495, 340, 4.9],
    [1570, 343, 5.2]
]

In [62]:
cars

[[1945, 560, 4.3], [1495, 340, 4.9], [1570, 343, 5.2]]

In [64]:
X = np.array(cars)
X

array([[1945. ,  560. ,    4.3],
       [1495. ,  340. ,    4.9],
       [1570. ,  343. ,    5.2]])

In [67]:
y = X[0]
y

array([1945. ,  560. ,    4.3])

In [70]:
weight = [0.00447524752478956, -0.0118811881188827, 2.24910891085849]
a = np.array(weight)
a

array([ 0.00447525, -0.01188119,  2.24910891])

In [72]:
X @ a 

array([11.72205941, 13.67152475, 14.64625743])